name: portfolio_website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.1
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: MartianMono
      fonts:
        - asset: assets/fonts/MartianMono-Thin.ttf
        - asset: assets/fonts/MartianMono-Bold.ttf
        - asset: assets/fonts/MartianMono-SemiBold.ttf
        - asset: assets/fonts/MartianMono-ExtraBold.ttf
        - asset: assets/fonts/MartianMono-ExtraLight.ttf
        - asset: assets/fonts/MartianMono-Light.ttf
        - asset: assets/fonts/MartianMono-Medium.ttf
        - asset: assets/fonts/MartianMono-Regular.ttf

